spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret-key:

server:
  port: 8080
